// Tony Hawk's Pro Skater 2 sheet — the skater, every pose the run needs. All
// frames are 16x24 facing right; the app plants each bottom-center and applies
// board/body spin with a canvas transform, so these are authored upright.
// Authored per README; common.ts is the reference for the conventions.

import type { SpriteDef } from './sprite';

// Rolling push, 2 frames — the back foot kicks off between beats.
export const SKATER_PUSH: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSSSSSk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '....kSSk........',
      '...kJJJJk.......',
      '..kkJJJJkk......',
      '.kJJJJJJJJk.....',
      '.kwJJJJJJJk.....',
      '.kJJJJJJJjk.....',
      '..kJJJJJJk......',
      '..kjJJJjk.......',
      '...kPPPPk.......',
      '...kPPPPk.......',
      '...kP..Pk.......',
      '..kPk..kPk......',
      '..kPk..kPk......',
      '..kwk..kwk......',
      '..kwk..kwk......',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '..e.e....e.e....',
    ],
    [
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSSSSSk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '....kSSk........',
      '...kJJJJk.......',
      '..kkJJJJkk......',
      '.kJJJJJJJJk.....',
      '.kwJJJJJJJk.....',
      '.kJJJJJJJjk.....',
      '..kJJJJJJk......',
      '..kjJJJjk.......',
      '...kPPPPk.......',
      '...kPPPPk.......',
      '...kP..Pk.......',
      '..kPk..kPk......',
      '.kPk....kPk.....',
      '.kwk....kPk.....',
      '.kwk....kwk.....',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '..e.e....e.e....',
    ],
  ],
};

// Loading the ollie — knees deep, weight low over the deck.
export const SKATER_CROUCH: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '..kkJJJJkk......',
      '.kJJJJJJJJk.....',
      '.kwJJJJJJJk.....',
      '.kJJJJJJJjk.....',
      '..kJJJJJJk......',
      '..kjPPPjk.......',
      '.kPPPPPPPPk.....',
      '.kPPk..kPPk.....',
      '.kPk....kPk.....',
      '.kwk....kwk.....',
      '.kwk....kwk.....',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '..e.e....e.e....',
    ],
  ],
};

// Popped into the air, arms out, board snug under the feet.
export const SKATER_OLLIE: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSSSSSk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '....kSSk........',
      '...kJJJJk.......',
      '.kkJJJJJJkk.....',
      'kJJJJJJJJJJk....',
      '.kwJJJJJJJk.....',
      '..kJJJJJJk......',
      '..kjJJJjk.......',
      '...kPPPPk.......',
      '...kPPPPk.......',
      '...kP..Pk.......',
      '..kPk..kPk......',
      '..kPk..kPk......',
      '..kPk..kPk......',
      '..kwk..kwk......',
      '..kwk..kwk......',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '..e.e....e.e....',
    ],
  ],
};

// Kickflip, 2 frames — the deck flips over under lifted feet.
export const SKATER_KICKFLIP: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSSSSSk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '....kSSk........',
      '...kJJJJk.......',
      '.kkJJJJJJkk.....',
      'kJJJJJJJJJJk....',
      '.kwJJJJJJJk.....',
      '..kJJJJJJk......',
      '..kjJJJjk.......',
      '...kPPPPk.......',
      '...kPPPPk.......',
      '...kP..Pk.......',
      '..kPk..kPk......',
      '..kPk..kPk......',
      '..kwk..kwk......',
      '..kwk..kwk......',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '..e.e....e.e....',
      '................',
    ],
    [
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSSSSSk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '....kSSk........',
      '...kJJJJk.......',
      '.kkJJJJJJkk.....',
      'kJJJJJJJJJJk....',
      '.kwJJJJJJJk.....',
      '..kJJJJJJk......',
      '..kjJJJjk.......',
      '...kPPPPk.......',
      '...kPPPPk.......',
      '...kP..Pk.......',
      '..kPk..kPk......',
      '..kPk..kPk......',
      '..kwk..kwk......',
      '..kwk..kwk......',
      '.kbbbbbbbbbbk...',
      '.kooooooooook...',
      '.e.e......e.e...',
      '................',
    ],
  ],
};

// Grab (Method / Christ Air) — folded up with a hand on the board.
export const SKATER_GRAB: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '................',
      '................',
      '................',
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '..kkJJJJkk......',
      '.kJJJJJJJJk.....',
      '.kwJJJJJJJk.....',
      '.kJJJJJJJjk.....',
      '..kJJJJJJk......',
      '..kjPPPPjk......',
      '.kPPPPPPPPk.....',
      '.kPk....kPk.....',
      '.kwk.SS.kwk.....',
      '..k.kSSk.k......',
      '...kooook.......',
      '..kbbbbbbk......',
      '...e....e.......',
      '................',
      '................',
      '................',
    ],
  ],
};

// Low 50-50 grind, arms flung wide to hold the balance.
export const SKATER_GRIND: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      'kk.kkJJkk.kk....',
      '.kkJJJJJJkk.....',
      '..kJJJJJJk......',
      '..kwJJJJjk......',
      '..kjJJJjk.......',
      '.kPPPPPPPPk.....',
      '.kPk....kPk.....',
      '.kwk....kwk.....',
      '.kwk....kwk.....',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '..e.e....e.e....',
      '................',
    ],
  ],
};

// Manual wheelie — leaning back with the nose lifted.
export const SKATER_MANUAL: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '................',
      '................',
      '.....kkk........',
      '....kHHHk.......',
      '...kHHHHHk......',
      '...kSwwSSk......',
      '...kSSSSsk......',
      '...kJJJJk.......',
      '..kkJJJJkk......',
      '.kJJJJJJJk......',
      '.kwJJJJJjk......',
      '.kJJJJJJjk......',
      '..kJJJJJk.......',
      '..kjPPPjk.......',
      '..kPPPPPk.......',
      '..kPP.PPk.......',
      '.kPk...kPk......',
      '.kwk...kPk......',
      '.kwk...kwk......',
      '.kwk...kwk...oo.',
      '.kooooooooook...',
      '.kbbbbbbbbbbk...',
      '.e.e............',
      '................',
    ],
  ],
};

// Bail, 2 frames — the tumble and the slide, board flung clear.
export const SKATER_BAIL: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '................',
      '................',
      '................',
      '.......oo.......',
      '......obbo......',
      '................',
      '................',
      '................',
      '....kk.....k....',
      '...kSSk...kJk...',
      '...kSSk..kJJk...',
      '..kkJJJJkkJk....',
      '.kJJJJJJJJJk....',
      '.kPPJJJJPPPk....',
      'kPPk.kPPkkkk....',
      'kwk...kwk.......',
      '................',
      '.....wwww.......',
      '...wwwwwwww.....',
      '..wwwwwwwwww....',
      '.wwwwwwwwwwww...',
      'wwwwwwwwwwwwww..',
      'wwwwwwwwwwwwwwww',
      '................',
    ],
    [
      '................',
      '................',
      '................',
      '................',
      '.........oo.....',
      '........obbo....',
      '................',
      '................',
      '.....k....kk....',
      '....kSSk..kJk...',
      '....kSSk.kJJk...',
      '...kkJJJkkJJk...',
      '..kJJJJJJJJk....',
      '..kPPJJJJPPk....',
      '.kPPkkPPk.kk....',
      '.kwk..kwk.......',
      '................',
      '......wwww......',
      '....wwwwwwww....',
      '...wwwwwwwwww...',
      '..wwwwwwwwwwww..',
      '.wwwwwwwwwwwwww.',
      'wwwwwwwwwwwwwwww',
      '................',
    ],
  ],
};

// The 900 — a tight tuck the app spins with a canvas transform.
export const SKATER_900: SpriteDef = {
  palette: { k: '#1c1a17', w: '#f4f4ec', S: '#f0c49a', s: '#d9a066', H: '#3a6ea5', J: '#d63a2f', j: '#9e2820', P: '#33373f', o: '#e8952a', b: '#b06a1e', e: '#e8c23a' },
  frames: [
    [
      '................',
      '................',
      '................',
      '......kkk.......',
      '.....kHHHk......',
      '....kHHHHHk.....',
      '....kSwwSk......',
      '....kSSSSk......',
      '...kkJJJJkk.....',
      '..kJJJJJJJJk....',
      '..SJJJJJJJJS....',
      '..kSPPPPPPSk....',
      '...kPPPPPPk.....',
      '...kwkooowk.....',
      '....kboobk......',
      '.....e..e.......',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
};

/** Every sprite in this sheet, for the validate-all test and demo listings. */
export const TONYHAWK_SPRITES: Record<string, SpriteDef> = {
  SKATER_PUSH,
  SKATER_CROUCH,
  SKATER_OLLIE,
  SKATER_KICKFLIP,
  SKATER_GRAB,
  SKATER_GRIND,
  SKATER_MANUAL,
  SKATER_BAIL,
  SKATER_900,
};
