import { lazy } from 'react';
import { AppDefinition } from '@/types/app';
import { setAppRegistry } from '@/hooks/useWindowManager';

// Placeholder app for apps not yet implemented
const PlaceholderApp = lazy(() => import('@/components/apps/placeholder/PlaceholderApp'));

// Real implementations
const DiskDefragmenter = lazy(() => import('@/components/apps/defrag/DiskDefragmenter'));
const TaskManagerApp = lazy(() => import('@/components/apps/task-manager/TaskManager'));
const RegistryEditor = lazy(() => import('@/components/apps/regedit/RegistryEditor'));
const DisplayProperties = lazy(() => import('@/components/apps/display-properties/DisplayProperties'));
const InternetExplorer = lazy(() => import('@/components/apps/ie5/InternetExplorer'));
const AOL = lazy(() => import('@/components/apps/aol/AOL'));
const AIM = lazy(() => import('@/components/apps/aim/AIM'));
const WinampApp = lazy(() => import('@/components/apps/winamp/Winamp'));
const NapsterApp = lazy(() => import('@/components/apps/napster/Napster'));
const NotepadApp = lazy(() => import('@/components/apps/notepad/Notepad'));
const CalculatorApp = lazy(() => import('@/components/apps/calculator/Calculator'));
const PaintApp = lazy(() => import('@/components/apps/paint/Paint'));
const MinesweeperApp = lazy(() => import('@/components/apps/minesweeper/Minesweeper'));
const MSDOSApp = lazy(() => import('@/components/apps/msdos/MSDOSPrompt'));
const ExplorerApp = lazy(() => import('@/components/apps/explorer/Explorer'));
const Word97App = lazy(() => import('@/components/apps/word97/Word97'));
const ExcelApp = lazy(() => import('@/components/apps/excel/Excel'));
const PowerPointApp = lazy(() => import('@/components/apps/powerpoint/PowerPoint'));
const Photoshop5App = lazy(() => import('@/components/apps/photoshop5/Photoshop5'));
const MacromediaFlashApp = lazy(() => import('@/components/apps/flash/MacromediaFlash'));
const FrontPageApp = lazy(() => import('@/components/apps/frontpage/FrontPage'));
const VisualBasic6App = lazy(() => import('@/components/apps/vb6/VisualBasic6'));
const WinRARApp = lazy(() => import('@/components/apps/winrar/WinRAR'));
const WinZipApp = lazy(() => import('@/components/apps/winzip/WinZip'));
const NeroBurningROMApp = lazy(() => import('@/components/apps/nero/NeroBurningROM'));
const NortonAntiVirusApp = lazy(() => import('@/components/apps/norton/NortonAntiVirus'));
const BonziBuddyApp = lazy(() => import('@/components/apps/bonzi-buddy/BonziBuddy'));
const AddRemoveProgramsApp = lazy(() => import('@/components/apps/add-remove-programs/AddRemovePrograms'));
const WordPadApp = lazy(() => import('@/components/apps/wordpad/WordPad'));
const CharacterMapApp = lazy(() => import('@/components/apps/character-map/CharacterMap'));
const SoundRecorderApp = lazy(() => import('@/components/apps/sound-recorder/SoundRecorder'));
const MediaPlayerApp = lazy(() => import('@/components/apps/media-player/MediaPlayer'));
const SolitaireApp = lazy(() => import('@/components/apps/solitaire/Solitaire'));
const FreeCellApp = lazy(() => import('@/components/apps/freecell/FreeCell'));
const HeartsApp = lazy(() => import('@/components/apps/hearts/Hearts'));
const ScanDiskApp = lazy(() => import('@/components/apps/scandisk/ScanDisk'));
const SystemInformationApp = lazy(() => import('@/components/apps/sysinfo/SystemInformation'));
const DeviceManagerApp = lazy(() => import('@/components/apps/device-manager/DeviceManager'));
const OregonTrailApp = lazy(() => import('@/components/apps/games/OregonTrail'));
const RollerCoasterTycoonApp = lazy(() => import('@/components/apps/games/RollerCoasterTycoon'));
const SimCityApp = lazy(() => import('@/components/apps/games/SimCity'));
const AgeOfEmpires2App = lazy(() => import('@/components/apps/games/AgeOfEmpires2'));
const Diablo2App = lazy(() => import('@/components/apps/games/Diablo2'));
const StarCraftApp = lazy(() => import('@/components/apps/games/StarCraft'));
const CommandConquerApp = lazy(() => import('@/components/apps/games/CommandConquer'));
const TonyHawk2App = lazy(() => import('@/components/apps/games/TonyHawk2'));
const SpaceCadetPinballApp = lazy(() => import('@/components/apps/pinball/SpaceCadetPinball'));
const RealPlayerApp = lazy(() => import('@/components/apps/realplayer/RealPlayer'));
const LimeWireApp = lazy(() => import('@/components/apps/limewire/LimeWire'));
const QuickTimePlayerApp = lazy(() => import('@/components/apps/quicktime/QuickTimePlayer'));
const OutlookExpressApp = lazy(() => import('@/components/apps/outlook/OutlookExpress'));
const MyComputerApp = lazy(() => import('@/components/apps/my-computer/MyComputer'));
const ControlPanelApp = lazy(() => import('@/components/apps/control-panel/ControlPanel'));

const apps: Record<string, AppDefinition> = {
  'notepad': {
    id: 'notepad',
    name: 'Notepad',
    icon: '/icons/notepad-32.svg',
    icon16: '/icons/notepad-16.svg',
    category: 'accessories',
    component: NotepadApp,
    defaultWindow: { title: 'Untitled - Notepad', width: 500, height: 400, minWidth: 250, minHeight: 200 },
    startMenuPath: ['Programs', 'Accessories'],
    desktopIcon: true,
    singleton: false,
  },
  'calculator': {
    id: 'calculator',
    name: 'Calculator',
    icon: '/icons/calculator-32.svg',
    icon16: '/icons/calculator-16.svg',
    category: 'accessories',
    component: CalculatorApp,
    defaultWindow: { title: 'Calculator', width: 260, height: 300, minWidth: 260, minHeight: 300 },
    startMenuPath: ['Programs', 'Accessories'],
    desktopIcon: true,
    singleton: true,
  },
  'paint': {
    id: 'paint',
    name: 'Paint',
    icon: '/icons/paint-32.svg',
    icon16: '/icons/paint-16.svg',
    category: 'accessories',
    component: PaintApp,
    defaultWindow: { title: 'untitled - Paint', width: 600, height: 480, minWidth: 300, minHeight: 250 },
    startMenuPath: ['Programs', 'Accessories'],
    desktopIcon: true,
    singleton: true,
  },
  'minesweeper': {
    id: 'minesweeper',
    name: 'Minesweeper',
    icon: '/icons/minesweeper-32.svg',
    icon16: '/icons/minesweeper-16.svg',
    category: 'games',
    component: MinesweeperApp,
    defaultWindow: { title: 'Minesweeper', width: 200, height: 260, minWidth: 200, minHeight: 260 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'solitaire': {
    id: 'solitaire',
    name: 'Solitaire',
    icon: '/icons/solitaire-32.svg',
    icon16: '/icons/solitaire-16.svg',
    category: 'games',
    component: SolitaireApp,
    defaultWindow: { title: 'Solitaire', width: 580, height: 440, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'msdos': {
    id: 'msdos',
    name: 'MS-DOS Prompt',
    icon: '/icons/msdos-32.svg',
    icon16: '/icons/msdos-16.svg',
    category: 'system',
    component: MSDOSApp,
    defaultWindow: { title: 'MS-DOS Prompt', width: 520, height: 340, minWidth: 320, minHeight: 200 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: false,
  },
  'explorer': {
    id: 'explorer',
    name: 'Windows Explorer',
    icon: '/icons/explorer-32.svg',
    icon16: '/icons/explorer-16.svg',
    category: 'system',
    component: ExplorerApp,
    defaultWindow: { title: 'Exploring - C:\\', width: 640, height: 480, minWidth: 350, minHeight: 250 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: false,
  },
  'ie5': {
    id: 'ie5',
    name: 'Internet Explorer',
    icon: '/icons/ie-32.svg',
    icon16: '/icons/ie-16.svg',
    category: 'internet',
    component: InternetExplorer,
    defaultWindow: { title: 'Microsoft Internet Explorer', width: 700, height: 500, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    quickLaunch: true,
    singleton: false,
  },
  'my-computer': {
    id: 'my-computer',
    name: 'My Computer',
    icon: '/icons/my-computer-32.svg',
    icon16: '/icons/my-computer-16.svg',
    category: 'system',
    component: MyComputerApp,
    defaultWindow: { title: 'My Computer', width: 500, height: 400, minWidth: 300, minHeight: 250 },
    desktopIcon: true,
    singleton: true,
  },
  'my-documents': {
    id: 'my-documents',
    name: 'My Documents',
    icon: '/icons/my-documents-32.svg',
    icon16: '/icons/my-documents-16.svg',
    category: 'system',
    component: PlaceholderApp,
    defaultWindow: { title: 'My Documents', width: 500, height: 400, minWidth: 300, minHeight: 250 },
    desktopIcon: true,
    singleton: true,
  },
  'recycle-bin': {
    id: 'recycle-bin',
    name: 'Recycle Bin',
    icon: '/icons/recycle-bin-32.svg',
    icon16: '/icons/recycle-bin-16.svg',
    category: 'system',
    component: PlaceholderApp,
    defaultWindow: { title: 'Recycle Bin', width: 400, height: 300, minWidth: 250, minHeight: 200 },
    desktopIcon: true,
    singleton: true,
  },
  'network-neighborhood': {
    id: 'network-neighborhood',
    name: 'Network Neighborhood',
    icon: '/icons/network-32.svg',
    icon16: '/icons/network-16.svg',
    category: 'system',
    component: PlaceholderApp,
    defaultWindow: { title: 'Network Neighborhood', width: 500, height: 400, minWidth: 300, minHeight: 250 },
    desktopIcon: true,
    singleton: true,
  },
  'aol': {
    id: 'aol',
    name: 'AOL',
    icon: '/icons/aol-32.svg',
    icon16: '/icons/aol-16.svg',
    category: 'internet',
    component: AOL,
    defaultWindow: { title: 'America Online', width: 640, height: 480, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Internet Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'aim': {
    id: 'aim',
    name: 'AIM',
    icon: '/icons/aim-32.svg',
    icon16: '/icons/aim-16.svg',
    category: 'internet',
    component: AIM,
    defaultWindow: { title: 'AIM Buddy List', width: 200, height: 400, minWidth: 150, minHeight: 250 },
    startMenuPath: ['Programs', 'Internet Tools'],
    quickLaunch: true,
    desktopIcon: true,
    singleton: true,
  },
  'winamp': {
    id: 'winamp',
    name: 'Winamp',
    icon: '/icons/winamp-32.svg',
    icon16: '/icons/winamp-16.svg',
    category: 'multimedia',
    component: WinampApp,
    defaultWindow: { title: 'Winamp', width: 275, height: 260, minWidth: 275, minHeight: 140 },
    startMenuPath: ['Programs', 'Multimedia'],
    quickLaunch: true,
    desktopIcon: true,
    singleton: true,
  },
  'word97': {
    id: 'word97',
    name: 'Microsoft Word',
    icon: '/icons/word-32.svg',
    icon16: '/icons/word-16.svg',
    category: 'productivity',
    component: Word97App,
    defaultWindow: { title: 'Document1 - Microsoft Word', width: 700, height: 500, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'excel': {
    id: 'excel',
    name: 'Microsoft Excel',
    icon: '/icons/excel-32.svg',
    icon16: '/icons/excel-16.svg',
    category: 'productivity',
    component: ExcelApp,
    defaultWindow: { title: 'Book1 - Microsoft Excel', width: 700, height: 500, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'control-panel': {
    id: 'control-panel',
    name: 'Control Panel',
    icon: '/icons/control-panel-32.svg',
    icon16: '/icons/control-panel-16.svg',
    category: 'system',
    component: ControlPanelApp,
    defaultWindow: { title: 'Control Panel', width: 500, height: 400, minWidth: 300, minHeight: 250 },
    startMenuPath: ['Settings'],
    desktopIcon: true,
    singleton: true,
  },
  'defrag': {
    id: 'defrag',
    name: 'Disk Defragmenter',
    icon: '/icons/defrag-32.svg',
    icon16: '/icons/defrag-16.svg',
    category: 'system',
    component: DiskDefragmenter,
    defaultWindow: { title: 'Disk Defragmenter', width: 500, height: 400, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Accessories', 'System Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'task-manager': {
    id: 'task-manager',
    name: 'Task Manager',
    icon: '/icons/taskman-32.svg',
    icon16: '/icons/taskman-16.svg',
    category: 'system',
    component: TaskManagerApp,
    defaultWindow: { title: 'Windows Task Manager', width: 400, height: 350, minWidth: 300, minHeight: 250 },
    desktopIcon: true,
    singleton: true,
  },
  'regedit': {
    id: 'regedit',
    name: 'Registry Editor',
    icon: '/icons/regedit-32.svg',
    icon16: '/icons/regedit-16.svg',
    category: 'system',
    component: RegistryEditor,
    defaultWindow: { title: 'Registry Editor', width: 600, height: 400, minWidth: 400, minHeight: 250 },
    startMenuPath: ['Programs', 'Accessories', 'System Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'display-properties': {
    id: 'display-properties',
    name: 'Display Properties',
    icon: '/icons/display-32.svg',
    icon16: '/icons/display-16.svg',
    category: 'system',
    component: DisplayProperties,
    defaultWindow: { title: 'Display Properties', width: 400, height: 440, minWidth: 380, minHeight: 400, resizable: false },
    startMenuPath: ['Settings', 'Control Panel'],
    desktopIcon: true,
    singleton: true,
  },
  'napster': {
    id: 'napster',
    name: 'Napster',
    icon: '/icons/napster-32.svg',
    icon16: '/icons/napster-16.svg',
    category: 'internet',
    component: NapsterApp,
    defaultWindow: { title: 'Napster', width: 550, height: 400, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Internet Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'powerpoint': {
    id: 'powerpoint',
    name: 'Microsoft PowerPoint',
    icon: '/icons/powerpoint-32.svg',
    icon16: '/icons/powerpoint-16.svg',
    category: 'productivity',
    component: PowerPointApp,
    defaultWindow: { title: 'Presentation1 - Microsoft PowerPoint', width: 750, height: 550, minWidth: 500, minHeight: 400 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'photoshop5': {
    id: 'photoshop5',
    name: 'Adobe Photoshop',
    icon: '/icons/photoshop-32.svg',
    icon16: '/icons/photoshop-16.svg',
    category: 'productivity',
    component: Photoshop5App,
    defaultWindow: { title: 'Adobe Photoshop', width: 800, height: 600, minWidth: 600, minHeight: 400 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'flash': {
    id: 'flash',
    name: 'Macromedia Flash',
    icon: '/icons/flash-32.svg',
    icon16: '/icons/flash-16.svg',
    category: 'productivity',
    component: MacromediaFlashApp,
    defaultWindow: { title: 'Macromedia Flash 5', width: 800, height: 600, minWidth: 600, minHeight: 400 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'frontpage': {
    id: 'frontpage',
    name: 'Microsoft FrontPage',
    icon: '/icons/frontpage-32.svg',
    icon16: '/icons/frontpage-16.svg',
    category: 'productivity',
    component: FrontPageApp,
    defaultWindow: { title: 'FrontPage Editor', width: 700, height: 500, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'vb6': {
    id: 'vb6',
    name: 'Visual Basic 6',
    icon: '/icons/vb6-32.svg',
    icon16: '/icons/vb6-16.svg',
    category: 'productivity',
    component: VisualBasic6App,
    defaultWindow: { title: 'Microsoft Visual Basic [design]', width: 800, height: 600, minWidth: 600, minHeight: 400 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'winrar': {
    id: 'winrar',
    name: 'WinRAR',
    icon: '/icons/winrar-32.svg',
    icon16: '/icons/winrar-16.svg',
    category: 'utilities',
    component: WinRARApp,
    defaultWindow: { title: 'WinRAR - archive.rar', width: 600, height: 400, minWidth: 400, minHeight: 250 },
    startMenuPath: ['Programs', 'WinRAR'],
    desktopIcon: true,
    singleton: false,
  },
  'winzip': {
    id: 'winzip',
    name: 'WinZip',
    icon: '/icons/winzip-32.svg',
    icon16: '/icons/winzip-16.svg',
    category: 'utilities',
    component: WinZipApp,
    defaultWindow: { title: 'WinZip - website.zip', width: 580, height: 380, minWidth: 400, minHeight: 250 },
    startMenuPath: ['Programs', 'WinZip'],
    desktopIcon: true,
    singleton: false,
  },
  'nero': {
    id: 'nero',
    name: 'Nero Burning ROM',
    icon: '/icons/nero-32.svg',
    icon16: '/icons/nero-16.svg',
    category: 'utilities',
    component: NeroBurningROMApp,
    defaultWindow: { title: 'Nero Burning ROM', width: 650, height: 450, minWidth: 450, minHeight: 300 },
    startMenuPath: ['Programs', 'Ahead Nero'],
    desktopIcon: true,
    singleton: true,
  },
  'norton': {
    id: 'norton',
    name: 'Norton AntiVirus',
    icon: '/icons/norton-32.svg',
    icon16: '/icons/norton-16.svg',
    category: 'utilities',
    component: NortonAntiVirusApp,
    defaultWindow: { title: 'Norton AntiVirus 2000', width: 450, height: 500, minWidth: 350, minHeight: 400 },
    startMenuPath: ['Programs', 'Norton AntiVirus'],
    desktopIcon: true,
    singleton: true,
  },
  'bonzi-buddy': {
    id: 'bonzi-buddy',
    name: 'BonziBUDDY',
    icon: '/icons/bonzi-32.svg',
    icon16: '/icons/bonzi-16.svg',
    category: 'internet',
    component: BonziBuddyApp,
    defaultWindow: { title: 'BonziBUDDY', width: 300, height: 420, minWidth: 250, minHeight: 350 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
  'add-remove-programs': {
    id: 'add-remove-programs',
    name: 'Add/Remove Programs',
    icon: '/icons/addremove-32.svg',
    icon16: '/icons/addremove-16.svg',
    category: 'system',
    component: AddRemoveProgramsApp,
    defaultWindow: { title: 'Add/Remove Programs Properties', width: 420, height: 450, minWidth: 380, minHeight: 350 },
    startMenuPath: ['Settings', 'Control Panel'],
    desktopIcon: true,
    singleton: true,
  },
  'wordpad': {
    id: 'wordpad',
    name: 'WordPad',
    icon: '/icons/wordpad-32.svg',
    icon16: '/icons/wordpad-16.svg',
    category: 'accessories',
    component: WordPadApp,
    defaultWindow: { title: 'Document - WordPad', width: 600, height: 450, minWidth: 350, minHeight: 250 },
    startMenuPath: ['Programs', 'Accessories'],
    desktopIcon: true,
    singleton: false,
  },
  'character-map': {
    id: 'character-map',
    name: 'Character Map',
    icon: '/icons/charmap-32.svg',
    icon16: '/icons/charmap-16.svg',
    category: 'accessories',
    component: CharacterMapApp,
    defaultWindow: { title: 'Character Map', width: 380, height: 340, minWidth: 320, minHeight: 280 },
    startMenuPath: ['Programs', 'Accessories'],
    desktopIcon: true,
    singleton: true,
  },
  'sound-recorder': {
    id: 'sound-recorder',
    name: 'Sound Recorder',
    icon: '/icons/soundrec-32.svg',
    icon16: '/icons/soundrec-16.svg',
    category: 'accessories',
    component: SoundRecorderApp,
    defaultWindow: { title: 'Sound - Sound Recorder', width: 280, height: 220, minWidth: 280, minHeight: 220, resizable: false },
    startMenuPath: ['Programs', 'Accessories', 'Multimedia'],
    desktopIcon: true,
    singleton: true,
  },
  'media-player': {
    id: 'media-player',
    name: 'Windows Media Player',
    icon: '/icons/mediaplayer-32.svg',
    icon16: '/icons/mediaplayer-16.svg',
    category: 'multimedia',
    component: MediaPlayerApp,
    defaultWindow: { title: 'Windows Media Player', width: 420, height: 380, minWidth: 300, minHeight: 280 },
    startMenuPath: ['Programs', 'Accessories', 'Multimedia'],
    desktopIcon: true,
    singleton: true,
  },
  'freecell': {
    id: 'freecell',
    name: 'FreeCell',
    icon: '/icons/freecell-32.svg',
    icon16: '/icons/freecell-16.svg',
    category: 'games',
    component: FreeCellApp,
    defaultWindow: { title: 'FreeCell', width: 580, height: 440, minWidth: 480, minHeight: 350 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'hearts': {
    id: 'hearts',
    name: 'Hearts',
    icon: '/icons/hearts-32.svg',
    icon16: '/icons/hearts-16.svg',
    category: 'games',
    component: HeartsApp,
    defaultWindow: { title: 'The Microsoft Hearts Network', width: 580, height: 480, minWidth: 450, minHeight: 380 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'scandisk': {
    id: 'scandisk',
    name: 'ScanDisk',
    icon: '/icons/scandisk-32.svg',
    icon16: '/icons/scandisk-16.svg',
    category: 'system',
    component: ScanDiskApp,
    defaultWindow: { title: 'ScanDisk', width: 420, height: 440, minWidth: 350, minHeight: 350 },
    startMenuPath: ['Programs', 'Accessories', 'System Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'sysinfo': {
    id: 'sysinfo',
    name: 'System Information',
    icon: '/icons/sysinfo-32.svg',
    icon16: '/icons/sysinfo-16.svg',
    category: 'system',
    component: SystemInformationApp,
    defaultWindow: { title: 'Microsoft System Information', width: 600, height: 400, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Accessories', 'System Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'device-manager': {
    id: 'device-manager',
    name: 'Device Manager',
    icon: '/icons/devmgr-32.svg',
    icon16: '/icons/devmgr-16.svg',
    category: 'system',
    component: DeviceManagerApp,
    defaultWindow: { title: 'System Properties - Device Manager', width: 420, height: 480, minWidth: 350, minHeight: 350 },
    startMenuPath: ['Settings', 'Control Panel'],
    desktopIcon: true,
    singleton: true,
  },
  'oregon-trail': {
    id: 'oregon-trail',
    name: 'Oregon Trail',
    icon: '/icons/oregon-trail-32.svg',
    icon16: '/icons/oregon-trail-16.svg',
    category: 'era-games',
    component: OregonTrailApp,
    defaultWindow: { title: 'The Oregon Trail', width: 550, height: 400, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'rollercoaster-tycoon': {
    id: 'rollercoaster-tycoon',
    name: 'RollerCoaster Tycoon',
    icon: '/icons/rct-32.svg',
    icon16: '/icons/rct-16.svg',
    category: 'era-games',
    component: RollerCoasterTycoonApp,
    defaultWindow: { title: 'RollerCoaster Tycoon', width: 500, height: 450, minWidth: 350, minHeight: 350 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'simcity': {
    id: 'simcity',
    name: 'SimCity 2000',
    icon: '/icons/simcity-32.svg',
    icon16: '/icons/simcity-16.svg',
    category: 'era-games',
    component: SimCityApp,
    defaultWindow: { title: 'SimCity 2000', width: 550, height: 450, minWidth: 400, minHeight: 350 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'age-of-empires-2': {
    id: 'age-of-empires-2',
    name: 'Age of Empires II',
    icon: '/icons/aoe2-32.svg',
    icon16: '/icons/aoe2-16.svg',
    category: 'era-games',
    component: AgeOfEmpires2App,
    defaultWindow: { title: 'Age of Empires II: The Age of Kings', width: 500, height: 480, minWidth: 350, minHeight: 380 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'diablo-2': {
    id: 'diablo-2',
    name: 'Diablo II',
    icon: '/icons/diablo2-32.svg',
    icon16: '/icons/diablo2-16.svg',
    category: 'era-games',
    component: Diablo2App,
    defaultWindow: { title: 'Diablo II', width: 480, height: 500, minWidth: 350, minHeight: 400 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'starcraft': {
    id: 'starcraft',
    name: 'StarCraft',
    icon: '/icons/starcraft-32.svg',
    icon16: '/icons/starcraft-16.svg',
    category: 'era-games',
    component: StarCraftApp,
    defaultWindow: { title: 'StarCraft', width: 480, height: 420, minWidth: 350, minHeight: 350 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'command-conquer': {
    id: 'command-conquer',
    name: 'C&C: Red Alert',
    icon: '/icons/cnc-32.svg',
    icon16: '/icons/cnc-16.svg',
    category: 'era-games',
    component: CommandConquerApp,
    defaultWindow: { title: 'Command & Conquer: Red Alert', width: 500, height: 430, minWidth: 400, minHeight: 350 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'tony-hawk-2': {
    id: 'tony-hawk-2',
    name: "Tony Hawk's Pro Skater 2",
    icon: '/icons/thps2-32.svg',
    icon16: '/icons/thps2-16.svg',
    category: 'era-games',
    component: TonyHawk2App,
    defaultWindow: { title: "Tony Hawk's Pro Skater 2", width: 450, height: 450, minWidth: 300, minHeight: 350 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'pinball': {
    id: 'pinball',
    name: '3D Pinball',
    icon: '/icons/pinball-32.svg',
    icon16: '/icons/pinball-16.svg',
    category: 'games',
    component: SpaceCadetPinballApp,
    defaultWindow: { title: '3D Pinball for Windows - Space Cadet', width: 340, height: 560, minWidth: 300, minHeight: 450 },
    startMenuPath: ['Programs', 'Games'],
    desktopIcon: true,
    singleton: true,
  },
  'realplayer': {
    id: 'realplayer',
    name: 'RealPlayer',
    icon: '/icons/realplayer-32.svg',
    icon16: '/icons/realplayer-16.svg',
    category: 'multimedia',
    component: RealPlayerApp,
    defaultWindow: { title: 'RealPlayer', width: 380, height: 340, minWidth: 300, minHeight: 280 },
    startMenuPath: ['Programs', 'Multimedia'],
    desktopIcon: true,
    singleton: true,
  },
  'limewire': {
    id: 'limewire',
    name: 'LimeWire',
    icon: '/icons/limewire-32.svg',
    icon16: '/icons/limewire-16.svg',
    category: 'internet',
    component: LimeWireApp,
    defaultWindow: { title: 'LimeWire', width: 550, height: 420, minWidth: 400, minHeight: 300 },
    startMenuPath: ['Programs', 'Internet Tools'],
    desktopIcon: true,
    singleton: true,
  },
  'quicktime': {
    id: 'quicktime',
    name: 'QuickTime Player',
    icon: '/icons/quicktime-32.svg',
    icon16: '/icons/quicktime-16.svg',
    category: 'multimedia',
    component: QuickTimePlayerApp,
    defaultWindow: { title: 'QuickTime Player', width: 320, height: 280, minWidth: 280, minHeight: 240 },
    startMenuPath: ['Programs', 'Multimedia'],
    desktopIcon: true,
    singleton: true,
  },
  'outlook-express': {
    id: 'outlook-express',
    name: 'Outlook Express',
    icon: '/icons/outlook-32.svg',
    icon16: '/icons/outlook-16.svg',
    category: 'internet',
    component: OutlookExpressApp,
    defaultWindow: { title: 'Outlook Express', width: 700, height: 500, minWidth: 500, minHeight: 350 },
    startMenuPath: ['Programs'],
    desktopIcon: true,
    singleton: true,
  },
};

// Initialize the window manager with the registry
setAppRegistry(apps);

export function getApp(appId: string): AppDefinition | undefined {
  return apps[appId];
}

export function getAllApps(): AppDefinition[] {
  return Object.values(apps);
}

export function getAppsByCategory(category: string): AppDefinition[] {
  return Object.values(apps).filter((app) => app.category === category);
}

export function getDesktopApps(): AppDefinition[] {
  return Object.values(apps).filter((app) => app.desktopIcon);
}

export function getQuickLaunchApps(): AppDefinition[] {
  return Object.values(apps).filter((app) => app.quickLaunch);
}

export function getStartMenuApps(): AppDefinition[] {
  return Object.values(apps).filter((app) => app.startMenuPath);
}

export default apps;
